# Explicitly use the Node.js provider
providers = ["node"]

[variables]
NODE_VERSION = "24.13.0"
NIXPACKS_NODE_VERSION = "24.13.0"

[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
